[package]
name = "sudoku-solver"
version = "0.1.0"
authors = ["Nick Blantz <nicholasblantz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
bitvec = "1"
